[platformio]
default_envs = input_device, output_device

[env]
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
monitor_speed = 115200

[firmware]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#79ce473e1a8010ed8096388690222fd2c94858a6
board = pico
framework = arduino
board_build_core = earlephilhower
board_build_f_cpu = 133000000L
board_build_filesystem_size = 1m
lib_deps = nanopb/Nanopb@0.4.92
nanopb_protos = +<protocol/shift.proto>
extra_scripts = post:tools/check_firmware_budget.py

[env:input_device]
platform = ${firmware.platform}
board = ${firmware.board}
framework = ${firmware.framework}
board_build.core = ${firmware.board_build_core}
board_build.f_cpu = ${firmware.board_build_f_cpu}
board_build.filesystem_size = ${firmware.board_build_filesystem_size}
lib_deps = ${firmware.lib_deps}
custom_nanopb_protos = ${firmware.nanopb_protos}
extra_scripts = ${firmware.extra_scripts}
build_flags =
  ${env.build_flags}
  -D IS_INPUT_DEVICE
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0

[env:output_device]
platform = ${firmware.platform}
board = ${firmware.board}
framework = ${firmware.framework}
board_build.core = ${firmware.board_build_core}
board_build.f_cpu = ${firmware.board_build_f_cpu}
board_build.filesystem_size = ${firmware.board_build_filesystem_size}
lib_deps = ${firmware.lib_deps}
custom_nanopb_protos = ${firmware.nanopb_protos}
extra_scripts = ${firmware.extra_scripts}
build_flags =
  ${env.build_flags}
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0

[env:native]
platform = native@1.2.1
test_framework = unity
test_build_src = no