syntax = "proto3";

import "nanopb.proto";

message Empty {
}

message IndexedValue {
  uint32 index = 1;
  uint32 value = 2;
}

message ResetCommand {
  uint32 device = 1;
  bool broadcast = 2;
}


message GraphBeginCommand {
  uint32 transfer_id = 1;
  uint32 generation = 2;
  uint32 image_size = 3;
  uint32 format = 4;
  uint32 executor_api = 5;
  uint32 expected_devices = 6;
  uint32 checksum = 7;
}

message GraphChunkCommand {
  uint32 transfer_id = 1;
  uint32 sequence = 2;
  bytes data = 3 [(nanopb).max_size = 4];
}

message GraphFinishCommand {
  uint32 transfer_id = 1;
  uint32 sequence_count = 2;
}

message GraphTransferCommand {
  uint32 transfer_id = 1;
}

message GraphIdentityCommand {
  uint32 generation = 1;
  uint32 checksum = 2;
  uint32 expected_devices = 3;
}

message GraphStatusCommand {
  uint32 transfer_id = 1;
}

message HostCommand {
  reserved 6, 7, 8;
  reserved "upsert_trigger", "remove_trigger", "clear_triggers";
  oneof command {
    Empty health_check = 1;
    IndexedValue set_pin = 2;
    IndexedValue set_byte = 3;
    ResetCommand reset = 4;
    Empty status = 5;
    GraphBeginCommand graph_begin = 9;
    GraphChunkCommand graph_chunk = 10;
    GraphFinishCommand graph_finish = 11;
    GraphTransferCommand graph_abort = 12;
    Empty graph_activate = 13;
    GraphIdentityCommand graph_rollback = 14;
    GraphStatusCommand graph_status = 15;
  }
}

message InputStateEvent {
  uint32 device = 1;
  uint32 state = 2;
}

message StatusEvent {
  reserved 4;
  reserved "trigger_count";
  uint32 device = 1;
  bool input_device = 2;
  uint32 gpio_state = 3;
  uint32 rx_dropped = 5;
  uint32 tx_dropped = 6;
  uint32 bus_errors = 7;
  uint32 graph_generation = 8;
  uint32 graph_checksum = 9;
  GraphUpdateState update_state = 10;
  GraphStoreState store_state = 11;
  GraphStoreError store_error = 12;
  uint32 flow_accepted_events = 13;
  uint32 flow_evaluated_actions = 14;
  uint32 action_retries = 15;
  uint32 action_rejections = 16;
  uint32 executor_executed_actions = 17;
  uint32 executor_rejected_actions = 18;
}

enum GraphUpdateState {
  GRAPH_UPDATE_STATE_IDLE = 0;
  GRAPH_UPDATE_STATE_RECEIVING = 1;
  GRAPH_UPDATE_STATE_VALIDATING = 2;
  GRAPH_UPDATE_STATE_STAGED = 3;
  GRAPH_UPDATE_STATE_ACTIVE = 4;
  GRAPH_UPDATE_STATE_ROLLBACK = 5;
  GRAPH_UPDATE_STATE_REJECTED = 6;
}

enum GraphUpdateError {
  GRAPH_UPDATE_ERROR_NONE = 0;
  GRAPH_UPDATE_ERROR_CONFLICT = 1;
  GRAPH_UPDATE_ERROR_INVALID_DESCRIPTOR = 2;
  GRAPH_UPDATE_ERROR_STALE_GENERATION = 3;
  GRAPH_UPDATE_ERROR_STORAGE = 4;
  GRAPH_UPDATE_ERROR_OUT_OF_ORDER = 5;
  GRAPH_UPDATE_ERROR_CONFLICTING_CHUNK = 6;
  GRAPH_UPDATE_ERROR_MISSING_CHUNK = 7;
  GRAPH_UPDATE_ERROR_INVALID_IMAGE = 8;
  GRAPH_UPDATE_ERROR_TIMEOUT = 9;
  GRAPH_UPDATE_ERROR_NOT_STAGED = 10;
  GRAPH_UPDATE_ERROR_NOT_READY = 11;
  GRAPH_UPDATE_ERROR_SEND_FAILED = 12;
  GRAPH_UPDATE_ERROR_ABORTED = 13;
  GRAPH_UPDATE_ERROR_WRONG_ROLE = 14;
  GRAPH_UPDATE_ERROR_INCOMPATIBLE = 15;
  GRAPH_UPDATE_ERROR_RUNTIME = 16;
}

enum DeviceRole {
  DEVICE_ROLE_UNSPECIFIED = 0;
  DEVICE_ROLE_INPUT = 1;
  DEVICE_ROLE_OUTPUT = 2;
}

enum GraphStoreState {
  GRAPH_STORE_STATE_EMPTY = 0;
  GRAPH_STORE_STATE_RECEIVING = 1;
  GRAPH_STORE_STATE_STAGED = 2;
  GRAPH_STORE_STATE_ACTIVE = 3;
  GRAPH_STORE_STATE_INVALID = 4;
  GRAPH_STORE_STATE_ROLLBACK = 5;
}

enum GraphStoreError {
  GRAPH_STORE_ERROR_NONE = 0;
  GRAPH_STORE_ERROR_MOUNT = 1;
  GRAPH_STORE_ERROR_METADATA_READ = 2;
  GRAPH_STORE_ERROR_METADATA_CORRUPT = 3;
  GRAPH_STORE_ERROR_METADATA_WRITE = 4;
  GRAPH_STORE_ERROR_INVALID_ARGUMENT = 5;
  GRAPH_STORE_ERROR_BUSY = 6;
  GRAPH_STORE_ERROR_NO_SLOT = 7;
  GRAPH_STORE_ERROR_SLOT_OPEN = 8;
  GRAPH_STORE_ERROR_SLOT_WRITE = 9;
  GRAPH_STORE_ERROR_SLOT_CLOSE = 10;
  GRAPH_STORE_ERROR_SLOT_READ = 11;
  GRAPH_STORE_ERROR_INVALID_LENGTH = 12;
  GRAPH_STORE_ERROR_INVALID_CHECKSUM = 13;
  GRAPH_STORE_ERROR_INVALID_IMAGE = 14;
  GRAPH_STORE_ERROR_INTERRUPTED = 15;
  GRAPH_STORE_ERROR_NO_STAGED_GRAPH = 16;
  GRAPH_STORE_ERROR_NO_ROLLBACK_GRAPH = 17;
  GRAPH_STORE_ERROR_NO_ACTIVE_GRAPH = 18;
}

enum GraphNodeStatusPart {
  GRAPH_NODE_STATUS_PART_UNSPECIFIED = 0;
  GRAPH_NODE_STATUS_PART_CAPABILITIES = 1;
  GRAPH_NODE_STATUS_PART_STATE = 2;
  GRAPH_NODE_STATUS_PART_ACTIVE = 3;
  GRAPH_NODE_STATUS_PART_STAGED = 4;
  GRAPH_NODE_STATUS_PART_ROLLBACK = 5;
  GRAPH_NODE_STATUS_PART_MANIFESTS = 6;
  GRAPH_NODE_STATUS_PART_ROLLBACK_MANIFEST = 7;
  GRAPH_NODE_STATUS_PART_TRANSPORT_DROPS = 8;
  GRAPH_NODE_STATUS_PART_TRANSPORT_ERRORS = 9;
  GRAPH_NODE_STATUS_PART_RUNTIME_IDENTITY = 10;
  GRAPH_NODE_STATUS_PART_FLOW_COUNTERS = 11;
  GRAPH_NODE_STATUS_PART_ACTION_COUNTERS = 12;
  GRAPH_NODE_STATUS_PART_EXECUTOR_COUNTERS = 13;
}

message GraphNodeStatusEvent {
  uint32 device = 1;
  GraphNodeStatusPart part = 2;
  uint32 format = 3;
  uint32 executor_api = 4;
  DeviceRole role = 5;
  uint32 transfer_id = 6;
  GraphUpdateState update_state = 7;
  GraphUpdateError update_error = 8;
  GraphStoreState store_state = 9;
  GraphStoreError store_error = 10;
  uint32 generation = 11;
  uint32 checksum = 12;
  uint32 active_devices = 13;
  uint32 staged_devices = 14;
  uint32 rollback_devices = 15;
  uint32 rx_dropped = 16;
  uint32 tx_dropped = 17;
  uint32 bus_errors = 18;
  uint32 runtime_generation = 19;
  uint32 runtime_checksum = 20;
  uint32 flow_accepted_events = 21;
  uint32 flow_evaluated_actions = 22;
  uint32 action_retries = 23;
  uint32 action_rejections = 24;
  uint32 executor_executed_actions = 25;
  uint32 executor_rejected_actions = 26;
}

message GraphUpdateEvent {
  uint32 transfer_id = 1;
  uint32 generation = 2;
  uint32 checksum = 3;
  uint32 expected_devices = 4;
  uint32 ready_devices = 5;
  uint32 progressed_devices = 6;
  uint32 staged_devices = 7;
  uint32 rejected_devices = 8;
  uint32 active_devices = 9;
  uint32 rollback_devices = 10;
  uint32 missing_devices = 11;
  uint32 next_sequence = 12;
  uint32 sequence_count = 13;
  GraphUpdateState state = 14;
  GraphUpdateError error = 15;
  bool chunk_pending = 16;
}

message ErrorEvent {
  enum Code {
    reserved 6;
    reserved "TRIGGER_TABLE_FULL";
    UNKNOWN = 0;
    INVALID_FRAME = 1;
    INVALID_COMMAND = 2;
    OUT_OF_RANGE = 3;
    TRANSPORT = 4;
    STORAGE = 5;
    GRAPH_UPDATE = 7;
  }

  Code code = 1;
}

message AckEvent {
  enum Operation {
    reserved 5, 6, 7;
    reserved "UPSERT_TRIGGER", "REMOVE_TRIGGER", "CLEAR_TRIGGERS";
    NONE = 0;
    HEALTH_CHECK = 1;
    SET_PIN = 2;
    SET_BYTE = 3;
    RESET = 4;
    GRAPH_BEGIN = 8;
    GRAPH_CHUNK = 9;
    GRAPH_FINISH = 10;
    GRAPH_ABORT = 11;
    GRAPH_ACTIVATE = 12;
    GRAPH_ROLLBACK = 13;
    GRAPH_STATUS = 14;
  }

  Operation operation = 1;
  bool accepted = 2;
}

message DeviceEvent {
  oneof event {
    InputStateEvent input_state = 1;
    StatusEvent status = 2;
    ErrorEvent error = 3;
    AckEvent ack = 4;
    GraphUpdateEvent graph_update = 5;
    GraphNodeStatusEvent graph_node_status = 6;
  }
}
